# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_circulos_m_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia_m',
            name='reportado',
        ),
        migrations.AddField(
            model_name='denuncia_m',
            name='hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
